### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by YuPeiHenry** [CS2103-AY1819S1-W14-2/main#14]
Allocate screen space to show additional fields, such as images for rides. Highlight status of ride like a tag (with different color) and possibly wait time as well.

**Comment by keenlok** [comment]
Would this include replacing the filler image/page when user selects the ride? Or should that be included in another issue?

**Comment by YuPeiHenry** [comment]
> Would this include replacing the filler image/page when user selects the ride? Or should that be included in another issue?

Yeah I think this is quite appropriate for the filler image/page for rides.
