### ISSUE TITLE
Handle other characters in name field

### ISSUE THREAD

**Issue by keenlok** [CS2103-AY1819S1-W14-2/main#44]
Allow the app to handle things like punctuations and apostrophes since now the name can only handle alphanumeric characters and sometimes the rides' names would be something like Snow White's Adventures, or Peter Pan's Flight. 

I'm not sure about the priority, but I think can be something we do in the future. You're welcome to change it tho.

**Comment by YuPeiHenry** [comment]
Seems reasonable. As long as no "/" is involved, it should not be hard either, as current implementation needs them to denote fields.
