### ISSUE TITLE
General guidelines for docs

### ISSUE THREAD

**Issue by YuPeiHenry** [CS2103-AY1819S1-W14-2/main#65]
Outline
- [ ] Friendly greeting
- [ ] Include introduction
- [ ] Make glossary and keywords more comprehensive
- [ ] Guide people, point users and developers of different skill levels to different sections

Headers
- [ ] Use title case
- [ ] Add indentation to subheadings
- [ ] Ensure every heading does not have only 1 subheading
- [ ] Ensure all headers have at least 1 line of text below them
- [ ] Ensure all headers have equal significance (eg. Don't spend 1 header on a specific command when the rest are generic categories)
- [ ] Include benefits
- [ ] (UserGuide) Task oriented headings (adding ride, deleting ride, viewing ride...)

Language in descriptions and explanations
- [ ] Use active voice (you instead of third person)
- [ ] Use plain simple English, short sentences
- [ ] Clear and concise, no question beyond doubt
- [ ] Say what your product does, not what it is designed to do
- [ ] Mention what your functions are for, not how to use them

Points
- [ ] Avoid inappropriate use of numbers for bullet points
- [ ] Lead-in before numbering
- [ ] Highlight points, maybe using colored markup (eg. the components in the architecture, they are well hidden)
- [ ] Use imperative language (start with verbs) for steps

Content
- [ ] Include explanation about purpose/use/concept of this function
- [ ] Include advice/suggestions/tips
- [ ] Examples for all features
- [ ] Include a **walkthrough** of GUI for user guide

Figures
- [ ] Number "important" figures
- [ ] Use at least 1 sentence after the figure to make explicit reference, even if it is obvious.
- [ ] Draw boxes in figure to highlight something (Where is the output, what difference to expect, where to go for the next step...)

**Comment by keenlok** [comment]
- [ ] an about to explain what the UG is about
- [ ] before and after diagrams for commands in the user guide
- [ ] alphabetical order for the commands? or divide into categories
- [ ] quick start can have a walk through to encourage user to use the app?
